### PR TITLE
Fix sun/moon avoidance in issorb

### PR DESCRIPTION
**Pull request by peterbult**
The sun/moon avoidance did not work correctly. Swapping the source and
sun/moon in the separation calculation seems to fix this issue. Not sure
why...

### CODE REVIEW

**Comment by paulray** [comment]
Ooh! Our first pull request!  Thanks @peterbult!

I wrote this really quickly so I'm not surprised I got that wrong. I also don't understand quite how separation() works, as in why it is not commutative.  

When you say this fixes the issue, do you mean that it now agrees with the Viewing tool on HEASARC?

**Comment by peterbult** [comment]
That's right, it seems to agree with the viewing tool now. I only checked by rough eye-balling though, so there may be some fine scale offsets still.

**Comment by paulray** [comment]
This shows the asymmetry: 
```
In [16]: SunPos[0].separation(SourcePos)
Out[16]: <Angle 16.935903722433977 deg>

In [17]: SourcePos.separation(SunPos[0])
Out[17]: <Angle 145.51098771506307 deg>

In [22]: SunPos[0]
Out[22]: 
<SkyCoord (GCRS: obstime=2017-01-01T00:00:00.000, obsgeoloc=( 0.,  0.,  0.) m, obsgeovel=( 0.,  0.,  0.) m / s): (ra, dec, distance) in (deg, deg, AU)
    ( 281.44157267, -23.02030356,  0.98333791)>

In [23]: SourcePos
Out[23]: 
<SkyCoord (ICRS): (ra, dec) in deg
    ( 263.0079167, -24.7458333)>
```

But, I verified that usually for SkyCoords, separation works as expected:
```
In [4]:  c1 = SkyCoord('5h23m34.5s', '-69d45m22s', frame='icrs')

In [5]:  c2 = SkyCoord('6h23m34.5s', '-62d45m22s', frame='icrs')

In [6]: c1.separation(c2)
Out[6]: <Angle 9.195497897455505 deg>

In [7]: c2.separation(c1)
Out[7]: <Angle 9.195497897455505 deg>
```

It may have something to do with the obstime or obsgeoloc attributes of the SkyCoord, but I haven't been able to figure it out yet.

**Comment by paulray** [comment]
No, I think it must have to do with the GCRS frame for SunPos.  I don't see why that would matter for an angular separation, though.

**Comment by paulray** [comment]
Indeed, if you first do `SunPos.transform_to(ICRS)`, the asymmetry goes away.

**Pull request merged**
