### PR TITLE
Small fixes to ni_Htest_sortgti 

### PR DESCRIPTION
**Pull request by sguillot**

### CODE REVIEW

**Comment by paulray** [comment]
Looks good to me. @kerrm are you good with this?

**Comment by kerrm** [comment]
That all looks fine to me.  There's now some overlap between "savefile"
(ASCII) and "writeevents" (FITS) so perhaps we should choose more
descriptive names for these, e.g. "writeascii" and "writefits" or something
like that.

**Comment by sguillot** [comment]
Oh, that's right. I forgot about savefile.  I'll fix this!

**Comment by sguillot** [comment]
Actually, I had missed that you added the lines to save the event file (as ascii).  This is useful indeed.
But:
1) at the moment it is only performed in case of "dosearch".
2) more importantly, this only save the events file in the optimised energy range (eminbest, emaxbest), but there is some value to have the events of all PI within the optimised GTI selection. For example, if the optimal GTI selection is obtained for 0.3-1.2 keV, the lightcurve modellers might still want to use a broader energy range *within* the optimal GTI selection (even though it was obtained for a narrower energy range).

What do you think?

**Comment by kerrm** [comment]
I definitely agree that writing the full FITS file is preferable.  In fact,
this was something Mike requested and I added the "savefile" option as a
simple solution.  But having the FITS file is obviously much more useful
for spectral analysis etc.
On the two points
(1) this is probably an oversight, since I implemented for Mike, who is
almost always doing a search
(2) I don't think it would be easy to modify savefile to write out the full
dataset; I think it's better to rely on the external tools as you've done
in your implementation

**Comment by sguillot** [comment]
Ok, then I'll remove the savefile to only keep the full event file (as fits).
I have a couple more tweaks to add, like checking that heasoft is running *before* the grid search and not after. Since the grid search may take a loonnnng time, it's better to know before that one forgot to initiate the ftools.

**Comment by sguillot** [comment]
stupid question: can I make to pull requests from my fork  in a row? or this one needs to be approved before I can submit a second one?

**Comment by paulray** [comment]
Just add more commits and `git push`. Your new changes will be added to this PR

**Comment by kerrm** [comment]
Speeding up the grid search is on my TODO list!

**Comment by paulray** [comment]
OK, let me know if I should merge this now

**Comment by sguillot** [comment]
It's OK for me if @kerrm approves :-)

**Comment by kerrm** [comment]
I say go ahead and merge it.  If we find we want to make any changes, we'll
just put it in a future PR!

**Pull request merged**
