### PR TITLE
Replacing Basemap with Cartopy

### PR DESCRIPTION
**Pull request by sguillot**
After struggling again to get basemap installed on my new laptop, I decided to take care of the changes 😁

See #69

### CODE REVIEW

**Comment by paulray** [comment]
I just tried this in a virtualenv on my Mac.  It fails with this error:
```
% pip install cartopy    
Collecting cartopy
  Using cached Cartopy-0.20.2.tar.gz (10.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      Proj 8.0.0 must be installed.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
I then tried `port install proj8` and now I have proj 8.1.1, but the pip still fails the same way.
Will keep trying.

**Comment by paulray** [comment]
On my Linux (CentOS 7) box I get this error:
```
% pip install cartopy
Collecting cartopy
  Downloading Cartopy-0.20.2.tar.gz (10.8 MB)
     |████████████████████████████████| 10.8 MB 810 kB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /Software/bin/python3.7 /Software/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpuh45avqn
       cwd: /tmp/pip-install-_agy1h07/cartopy_15f3ab1c56ab4a16802e73d082005998
  Complete output (1 lines):
  GEOS version 3.4.2 is installed, but cartopy requires at least version 3.7.2.
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/f6/55/1e1c737dc9436b320deead73d1c455ddbb74b8b6992081863492f6f6378a/Cartopy-0.20.2.tar.gz#sha256=4d08c198ecaa50a6a6b109d0f14c070e813defc046a83ac5d7ab494f85599e35 (from https://pypi.org/simple/cartopy/) (requires-python:>=3.7). Command errored out with exit status 1: /Software/bin/python3.7 /Software/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpuh45avqn Check the logs for full command output.
```
In this case, geos is in `/usr/lib64/libgeos-3.4.2.so` and I'm not sure how to get CentOS to upgrade to a newer version.

**Comment by sguillot** [comment]
I didn't encounter any of these problems.  I suspect that I installed it with `conda install cartopy`. I'm not sure how to check that though.

**Comment by sguillot** [comment]
Actually `conda list` gives me:
```
cartopy                   0.20.2                   pypi_0    pypi
```
meaning that I installed it with `pip`.

**Comment by paulray** [comment]
Interesting. I didn't know you could install with pip in a conda environment. I wonder how it gets the binary dependencies. I guess you installed the geos and proj libraries via conda first?

**Comment by paulray** [comment]
When I install purely in conda it works.  And when I install purely in MacPorts, it works. I just have trouble with the pip installs because of the dependencies on non-python libraries that it has trouble installing.
But, matplotlib basemap is also a pain to install and at least cartopy is currently maintained, so I think I'll merge this.
If people can't get cartopy installed, they can just live without maps. Hopefully psrpipe will not crash but will just skip making the maps.

**Comment by paulray** [comment]
For some reason the latest cartopy required proj > 8.0 and that causes problems on many machines when trying to pip install: https://github.com/SciTools/cartopy/issues/1879

The solution for many people may be to do `pip install cartopy==0.18.0`. That let me install with pip on my Ubuntu machine. So far, on CentOS 7 it looks like I have to use conda or install geos and proj from source, which is a burden

**Pull request merged**
