### PR TITLE
Fractional X-Coords and File Input

### PR DESCRIPTION
**Pull request by champagne-cmd**
Script takes .csv or .txt input, outputs .csv and graph, and can handle fractional x-coordinates (finds the smallest difference in x-coordinates - in our case MJDs) and bins data in these increments, gaps are in the increments without data.

### CODE REVIEW

**Comment by paulray** [comment]
I'm not sure how this could have happened, but there are conflicts. Can you take a look?

**Comment by champagne-cmd** [comment]
That's odd, it marked basically all my changes as conflicts... well of course they conflict with the master, that's why I'm making the pull request... anyway, they are resolved now.

**Comment by paulray** [comment]
OK, merged. Make sure that 'master' is now all up to date. I hope I didn't mess anything up.

**Comment by champagne-cmd** [comment]
Ok I think it looks good. One thing is that the Allan Deviation Tests and fillgaps_examples notebooks are now broken as the inputs to the script have changed - I will modify these and include a test .txt file with them.

**Pull request merged**
